#!/bin/bash
# script to get a hugo docker set up with the whole documentation page 
# with your local repos documentation stuff mounted inside

REPO_NAME=$(basename "$(git rev-parse --show-toplevel)")
echo "Found repo: $REPO_NAME"

# get the absolute path to your local repos root
HOST_PATH=$(git rev-parse --show-toplevel)

if [ "$REPO_NAME" == "Documentation" ]; then
    # just copy everything over from Source
    HOST_PATH="$HOST_PATH/Source"
    DOCKER_PATH="/home/docsy/app"
else
    # other repos need to be mounted inside the repositories folder
    # there are already symlinks to deal with the proper linking
    DOCKER_PATH="/home/docsy/app/repositories/$REPO_NAME"
fi

echo "Mounting folder $HOST_PATH to $DOCKER_PATH"
MOUNT_CMD="$HOST_PATH:$DOCKER_PATH"

docker run -it -p 1313:1313 -v "$MOUNT_CMD" dolittle/documentation:latest

